version: "3.9"

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
    - MARIADB_ROOT_PASSWORD=Claro2025*
    - MARIADB_DATABASE=testdb
    - MARIADB_USER=testuser
    - MARIADB_PASSWORD=testpass
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
