version: "3.9"

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=proyecto_django.settings

  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: midb
      MYSQL_USER: mayra.soto
      MYSQL_PASSWORD: Claro2025*
    ports:
      - "3306:3306"
