version: "3.9"

services:
  solucionmeta-database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: solucionmeta-server
      MYSQL_USER: cpplasidso@solucionmeta-server
      MYSQL_PASSWORD: Claro2025*
      MYSQL_ROOT_PASSWORD: Claro2025*
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

