# Generated by Django 5.1.4 on 2025-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_credenciales_empresa_logseventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='allocation_configuration_id',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credenciales_empresa',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fecha_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
